### ISSUE TITLE
Support Faba box (MKI audio file)

### ISSUE THREAD

**Issue by soptikopava** [ZapDissaster/smp2mp3#12]
[ALGORITHM]
NAME=faba2
SOURCEEXT=.mki
DESTEXT=.mp3
OPERATIONSCOUNT=2
CHANGEID3=0
[OPERATION0]
TYPE=1
ROTATEDIRECTION=1
ROTATECOUNT=3
XORKEY=0x06,0xA0,0x23,0x04
[OPERATION1]
TYPE=0
ROTATEDIRECTION=0
ROTATECOUNT=0
XORKEY=0x06,0xA0,0x23,0x04

**Comment by ZapDissaster** [comment]
Added the Faba.key file to the list of key files. Thanks!
