### ISSUE TITLE
From hachette to lidl issue

### ISSUE THREAD

**Issue by Xristia** [ZapDissaster/smp2mp3#2]
Thank you for this program! My hachette speaker is not working. I have the lidl speaker. So i converted smp files from hachette to mp3, and then converted again to smp for lidl speaker. I tried rename the final smp files for lidl device but it doesn't work. Could you please help me? Thank you in advance!

**Comment by ZapDissaster** [comment]
Hi, I don't have the Lidl speaker, so I can not run tests on this but, as far as I understand, you must first rename the mp3 and then convert it to the Lidl format. Once the file is converted to the Lidl format, you can't rename it or it won't work.

Please let me know if this works so I can mark this issue as closed.

**Comment by idasyregresos** [comment]
Hola, tengo el altavoz de lidl.
he probado copiar los archivos csv en etiqetas nfc 213 pero no me funcionan...
