### ISSUE TITLE
Mr Men

### ISSUE THREAD

**Issue by DT-666** [ZapDissaster/smp2mp3#3]
Any update planned for the hachette Mr Men  serie ?

**Comment by PaulSka** [comment]
Hello @DT-666, it's work natively with version 3.4.10.12
I use Abecedario Keys.

**Comment by ZapDissaster** [comment]
Can anyone provide an example for the Mr Man files? and if possible a link to the official Mr. Man site?

**Comment by DT-666** [comment]
Hello, 

Here 2files: https://drive.google.com/drive/folders/1E56D4zhW7DpKmwGbp7mFf14TXNTDJyyF?usp=sharing

https://www.hachette-collections.com/fr-fr/collection-audio-monsieurmadame/?gclid=CjwKCAiA6Y2QBhAtEiwAGHybPWvIJPNljq8L5AwhCraspw1RSjzehnIIu1xI7jb3hKQZDgqTl37QAxoC-q4QAvD_BwE

and sound file : 
https://www.hachette-collections.com/fr-fr/pages/collections/14F/assets/medias/audio.mp3

**Comment by PaulSka** [comment]
@DT-666 It's works for you with Abecedario Keys ?

**Comment by DT-666** [comment]
@PaulSka. Sure it works with that key (i'm cheking all the mp3 today).

Thanks a lot ;)

**Comment by ZapDissaster** [comment]
Hi, As stated above, the Abecedario Keys should work with the Mr Men files.  Greetings.
