### ISSUE TITLE
Storie sonore della fattoria

### ISSUE THREAD

**Issue by knoppix85** [ZapDissaster/smp2mp3#4]
Hi! Thank you for your software. I used it to encode/decode mp3 files for the audiocube "Storie sonore della fattoria" (https://www.deagostini.com/it/prodotti/storie-sonore-animali-della-fattoria/V25883000000).
I found the XOR key and I want to share it with you. The key is: 0x44 0x33 0x22 0x11

I hope this helps someone else.

**Comment by ZapDissaster** [comment]
Thanks for the info, I'll add it to the documentation.
