### ISSUE TITLE
The MP3 Is unplayable

### ISSUE THREAD

**Issue by LowkeyMad** [ZapDissaster/smp2mp3#5]
So I have converted my .smp file to my .mp3 file, but the mp3 file is unplayable. I can't even open it on Audacity. I tried opening Raw Data, but this makes the audio quality very bad... I tried converting my .smp file to a .mp3 with and without normalizing.
Am I forgetting something?

**Comment by ZapDissaster** [comment]
You might use a different algorithm to decrypt the file. what kind of player (cube) do you have?
