### ISSUE TITLE
Change ID3v2.3 Tag not working on LIDL key

### ISSUE THREAD

**Issue by tiksustis** [ZapDissaster/smp2mp3#6]
Although the lidl key is working encryptionwise, the SMP file is unplayable. The button "Change ID3v2.3 Tag before encrypt" writes the correct tag but in ISO-8859-1 . For the file to be playable it need to be in UTF16.

One simple bypass is to uncheck the box and have the mp3 with a correct UTF16 tag beforehand, but i'm just reporting this for anyone who might wanna look into it, or has problems.

Thanks

**Comment by ZapDissaster** [comment]
Thanks for your input.
