### ISSUE TITLE
Encryption don't work with hachette blue cube

### ISSUE THREAD

**Issue by KurapikaShinji** [ZapDissaster/smp2mp3#7]
Hi !

I tried to encrypt a mp3 but it's not recognized by the audiocube.

I evend tried to decrypt a smp to mp3, then re-encrypt to smp, and the cube just give a snizzle sound when I put the figure (or a nfc tag).

Does somebody has the same issue ?

**Comment by ZapDissaster** [comment]
Hi, can you upload one of the original files to take a look at it?

**Comment by KurapikaShinji** [comment]
[T1122.zip](https://github.com/ZapDissaster/smp2mp3/files/14863500/T1122.zip)
Hi,
Here an original file from the editor (Hachette, for french Mr Men & Little Miss audio stories)

Thanks :)

**Comment by ZapDissaster** [comment]
I Used the following encription key (it's the one name "abecedario", it was used with the green cube in México): 
[Abecedario.zip](https://github.com/ZapDissaster/smp2mp3/files/14876544/Abecedario.zip) 
And it worked. Here's the sample file you sent decrypted: 
[T1122 - Dec.zip](https://github.com/ZapDissaster/smp2mp3/files/14876558/T1122.-.Dec.zip).

If you want to enter the encription key manually, here's how it must be: 
![image](https://github.com/ZapDissaster/smp2mp3/assets/78128624/ab59b6a4-4f1b-4c9c-977f-e0740641baf1)

You can test if you're using the right encryption key before converting the files by loading the file in the program and pressing the PLAY button. if it plays ok, then you have the right key.

![image](https://github.com/ZapDissaster/smp2mp3/assets/78128624/802cc8cb-b4d7-4f29-baf7-e3bbbb9b7bf5)

**Comment by ZapDissaster** [comment]
By the way, I like to collect the distinct collections in all the available languages. Is there any way you can send me the files on your SD card?

**Comment by KurapikaShinji** [comment]
Hi,

The problem I get is to encrypt, not decrypt.
I try to put musics and other stories on the cube, but it just snizzles.

So I already tried all algorithm in your smp2mp3 project, but it don't works :(

Ok for the SD card content, I'll make the full extract and upload this week end

**Comment by KurapikaShinji** [comment]
I managed to make it work :o

I checked "add filename to ID3..." and it's OK now.
It's been a month I tried, with oyooyo's tool, with yours, and it was just because I missed a checkbox :'(

Thanks for your help, I now have to make some tags for my little girl :)

(I won't forget about sending the original files)

**Comment by ZapDissaster** [comment]
I'm glad you made it work! I'll add this information to the project notes! And thanks agreeing to update the original files, I'll keep this Issue open so you can post the link to the files.

**Comment by KurapikaShinji** [comment]
Here is the download link for the 30 stories : https://1fichier.com/?tmncthpmo3m95iqj02z5

**Comment by ZapDissaster** [comment]
Thanks!
